Simplified configuration
wultra/powerauth-mobile-sdk pull request #534
Opened 2023-05-29 12:07 UTC by hvge

This PR adds support for simplified cryptographic configuration.

2023-06-06 13:46 UTC, kober32 requested changes
Looks OK (just one typo).

But it just seems like the change is not explained enough.

If there is legacy support for RN, why is a newer server needed?
Where (as a mobile developer) can I get the new configuration?
Why the change, what's the benefit (other than just having 1 config value)?

I'm pretty sure that a lot of developers will have these questions because they will upgrade the SDK (Android studio will tell them) and they won't understand what to do and if they should nag backend developers to upgrade.

2023-06-06 13:46 UTC, kober32 commented on include/PowerAuth/Session.h
> +         if session has a no valid setup.
Typo

2023-06-06 13:46 UTC, kober32 commented on include/PowerAuth/Session.h
> +
Formatting

2023-06-12 08:49 UTC, hvge commented
This is just a small piece related to 1.8.0 release. The new server will be needed due to #529. I created the migration document in advance, because we know that this future release will require server 1.5.0 and newer to operate properly.

2023-06-12 09:48 UTC, kober32 approved these changes
👍🏻

2023-06-12 09:56 UTC, hvge commented
I just fixed the grammar and the formatting in that header. We'll update the documentation as a part of [other tasks](https://github.com/wultra/powerauth-mobile-sdk/milestone/11) planned for 1.8. We declare the compatibility in the compatibility matrix for each branch of SDK, so If Android developer proactively upgrade to an incompatible version, then unfortunately it will not work. There's a new status endpoint planned for server 1.5, so we can introduce an error code indicating that mobile SDK is not compatible with the server.

2023-06-12 10:12 UTC, merged